In [1]:
import sys
sys.path.append("..")

In [2]:
import torch
from torch import nn
from model_utils.custom_attentions import NTMAtten_Layer, DotAtten_Layer

## NTM attention

In [3]:
keys = torch.rand(1, 10, 3)
values = torch.rand(1, 10, 3)
query = torch.rand(1, 1, 3)
test_layer = NTMAtten_Layer(embed_dim=3, window_size=3)
attn_mask, _ = test_layer.attention_mask(seq_lengths=torch.Tensor([8]), seq_length_max=10, window_size=2, query_index=3)
test_layer(query, values, keys, attn_mask=attn_mask)

(tensor([[[-0.3700, -0.4656, -0.0293]]], grad_fn=<UnsafeViewBackward>),
 tensor([[[0.0000],
          [0.1772],
          [0.1815],
          [0.2265],
          [0.2107],
          [0.2042],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000]]], grad_fn=<TransposeBackward0>))

## Dot attention

In [6]:
keys = torch.rand(1, 10, 3)
values = torch.rand(1, 10, 3)
query = torch.rand(1, 1, 3)
test_layer2 = DotAtten_Layer(embed_dim=3, window_size=3)
attn_mask2, _ = test_layer2.attention_mask(seq_lengths=torch.Tensor([8]), seq_length_max=10, window_size=2, query_index=3)
test_layer2(query, keys, values, attn_mask=attn_mask2)

(tensor([[[-0.2763,  0.0621, -0.5755]]], grad_fn=<UnsafeViewBackward>),
 tensor([[[0.0000],
          [0.2291],
          [0.2183],
          [0.2316],
          [0.2129],
          [0.2193],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000]]], grad_fn=<TransposeBackward0>))

## test torch's operation of sum two matrix with different length of time
If two metrix are different at one dimention's size, the operation is broadcast through that dim

In [7]:
input1 = torch.rand(2, 1, 3) 
input2 = torch.rand(2, 10, 3)
result1 = input1 + input2

result2 = []
for i in range(input2.size(1)):
    temp = input1 + input2[:, i:i+1, :]
    result2.append(temp)
    
result2 = torch.cat(result2, dim=1)

assert torch.equal(result1, result2)