In [1]:
import torch
import numpy as np
from warpctc_pytorch import CTCLoss

In [10]:
from torch import log_softmax, softmax

In [13]:
t = torch.rand([3, 4])

In [16]:
t

tensor([[0.8030, 0.9967, 0.2067, 0.8917],
        [0.4976, 0.4992, 0.9585, 0.0284],
        [0.3995, 0.4733, 0.6297, 0.5109]])

In [15]:
t.softmax(-1)

tensor([[0.2593, 0.3147, 0.1428, 0.2833],
        [0.2374, 0.2378, 0.3764, 0.1485],
        [0.2246, 0.2418, 0.2827, 0.2510]])

In [9]:
model = torch.nn.Linear(4, 5)
model.train()
print(model.training)
model.eval()
print(model.training)

True
False


In [2]:
costfunc = CTCLoss()

preds = torch.rand(100, 128, 37)
# input predict should be softmaxed
preds = torch.softmax(preds, dim=0, dtype=torch.float32)
preds = preds.to("cuda")
preds = preds.requires_grad_(True)

label_length = torch.from_numpy(np.random.randint(20, 80, 128, dtype=np.int32))
s = label_length.sum()
s = int(s)

labels = torch.from_numpy(np.random.randint(1, 36, (s,), dtype=np.int32))

# length of input. Since the input is a tensor, the input size of all_seq in one batch should be the same 
preds_size = torch.tensor([128 for i in range(128)], dtype=torch.int32)

loss = costfunc(preds, labels, preds_size, label_length)
loss.backward()
preds.grad

tensor([[[-5.9217e+01,  2.6168e-02, -1.7620e+01,  ..., -2.1196e-01,
           2.7001e-02,  2.6985e-02],
         [-1.4188e+02,  2.7052e-02, -2.1667e+01,  ..., -2.6427e+01,
           2.6948e-02,  2.6962e-02],
         [-3.0149e+01,  2.7156e-02, -2.2205e-01,  ...,  2.6966e-02,
           2.6981e-02,  2.7041e-02],
         ...,
         [-4.7550e-01,  2.7008e-02,  2.6979e-02,  ...,  2.7016e-02,
           2.6988e-02,  2.6973e-02],
         [-5.7200e-01,  2.7046e-02,  2.6949e-02,  ...,  2.7166e-02,
           2.6939e-02,  2.7189e-02],
         [-3.0327e-01,  2.6984e-02,  2.6975e-02,  ...,  2.6920e-02,
           2.6957e-02,  2.7077e-02]],

        [[-8.9617e+02,  1.1260e-03, -2.7600e+02,  ..., -4.4240e+00,
           2.6923e-02,  2.7049e-02],
         [-2.1263e+03,  2.7022e-02, -3.2548e+02,  ..., -3.7400e+02,
           2.7111e-02,  2.7017e-02],
         [-7.4793e+02,  2.7092e-02, -5.9343e+00,  ...,  2.6944e-02,
           2.7086e-02,  2.7055e-02],
         ...,
         [-3.5144e-01,  2